In [8]:
import numpy as np

# 1 D array or Vector

In [6]:
ls=[1,2,3,4]

In [9]:
np.array(ls)

array([1, 2, 3, 4])

# 2D array or Matrices

In [10]:
ls1=[[1,2],[3,4],[5,6]]

In [11]:
np.array(ls1)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Arange function start,stop and step

In [42]:
arr1=np.arange(10,51,2)

In [ ]:
# Or single parameter works like start only

In [97]:
arr2=np.arange(9)

In [98]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
print(arr1)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# Inbuild functions for Zero and Ones

In [94]:
np.zeros(11)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [45]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [95]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Add matrix

In [ ]:
# Matrix of ones

In [30]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Create matrix of 0-8 in 3x3 

In [59]:
np.linspace(0,8,9).reshape(3,3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
#Actual solution

In [96]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
np.random.rand(1)

array([0.49984866])

# Linspace to add the elements evenly spaces start , end and splits

In [ ]:
# Standard normal distribution vs gausian

In [76]:
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [103]:
np.arange(1,101).reshape(10,10)/10

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [88]:
mat=np.linspace(0.01,1,100).reshape(10,10)

In [91]:
print (mat)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


# Get a range from given matrix

In [104]:
arr3=np.arange(1,26).reshape(5,5)

In [105]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [115]:
arr3[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Get column data only

In [121]:
arr3[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [124]:
arr3[-1:]

array([[21, 22, 23, 24, 25]])

In [128]:
arr3[3:5,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# get only one element only

In [117]:
arr3[3,4]

20

# Sum of an array elements

In [89]:
np.sum(mat)

50.5

In [129]:
mat.sum()


50.5

# Standard Deviation of elements in matrix

In [90]:
np.std(mat)

0.2886607004772212

# Eye Matix

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# random matrix, gausian

In [72]:
np.random.randn(2)

array([2.14901044, 0.03147274])

In [73]:
np.random.rand(2)

array([0.77188272, 0.47057508])

In [33]:
np.random.randint(1,100,10)

array([56,  4, 98, 73, 51, 29, 72, 47, 60, 80])

In [ ]:
# slicing of arr, broadcast, copy of arr,bool arr,conditional selection of arr

In [ ]:
np.savetext('test.out',sports, delimiter=',') 